<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AddMedia extends Seeder{

    public function run(){

        Schema::disableForeignKeyConstraints();
        DB::table('media')->truncate();

        DB::table('media')->insert([
            [
                'real_name' => 'seeder.png',
                'system_name' => 'seeder_image.png',
                'base_path' => url('public/media'),
                'alt_name' => 'seeder_pic',
                'extension' => '.png',
                'size' => '1024',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_1.jpg',
                'system_name' => 'doc_1.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_1.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_2.jpg',
                'system_name' => 'doc_2.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_2.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_3.jpg',
                'system_name' => 'doc_3.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_3.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_4.jpg',
                'system_name' => 'doc_4.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_4.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_5.jpg',
                'system_name' => 'doc_5.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_5.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_6.jpg',
                'system_name' => 'doc_6.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_6.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_7.jpg',
                'system_name' => 'doc_7.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_7.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_8.jpg',
                'system_name' => 'doc_8.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_8.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_9.jpg',
                'system_name' => 'doc_9.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_9.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_10.jpg',
                'system_name' => 'doc_10.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_10.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_11.jpg',
                'system_name' => 'doc_11.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_11.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ],
            [
                'real_name' => 'doc_12.jpg',
                'system_name' => 'doc_12.jpg',
                'base_path' => url('public/media'),
                'alt_name' => 'doc_12.jpg',
                'extension' => '.jpg',
                'size' => '100',
                'description' => 'abc',
                'created_at' => now(),
                'deleted_at' => null,
                'created_by' => 1,
            ]
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
